### ISSUE TITLE
Monero

### ISSUE THREAD

**Issue by masterofdaemon** [MathieuMailhos/GoBtcMiner#2]
Hello, how can i remade it to monero?

**Comment by mmailhos** [comment]
Hello,
I do not know Monero into the details but its CryptoNight PoW hash algorithm and its obfuscation technique makes it much different from Bitcoin and a complete rewrite might me appropriate.

However, that's an interesting topic since Monero can be pretty efficient with CPU, I'll look into it in details and open a new project for that.
